### ISSUE TITLE
Localhost switch in profile settings

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#173]
- Rename `Remote Port`->`DebugServer Port`
- Add `Localhost` switch in `Profiles`->`General`. When set:
   - `Remote Machine Address:` is greyd out
   - Value `localhost` is used for connetion

**Comment by timlathy** [comment]
#175 lets us perform all local steps (execute, read debug data, etc.) without connecting to the debug server.

Instead of using `localhost` for connection, this switch can force all remote steps to be done locally, so:
* Execute Remote becomes Execute Local
* Copy from Remote and Copy to Local become local to local copies
* Deployment ("Copy sources to remote") gets disabled
* `$ENVR()` macros are evaluated the same way as `$ENV()`

**Comment by Kirpich30000** [comment]
Sounds good
